### ISSUE TITLE
Locks OBS up after 

### ISSUE THREAD

**Issue by xxameht** [Crowsinc/LiveVisionKit#16] opened 2023-02-24 05:24 UTC
**System/Software Setup**
 - **LiveVisionKit Version:** *1.2.2*
 - **OBS Studio Version:** *29.0.2*
 - **OS:** *Windows 11*
 - **GPU:** *RTX 2070*
 - **CPU:** *Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz*

**OBS Log:**: *[A link to the OBS log corresponding with the issue. This can be done through OBS by going to - Help -> Log Files -> Upload Current Log File](https://obsproject.com/logs/5XU5tdA7t1xu48xL)*

**Issue Description**
*Filter runs perfectly for approx 5 to 10 mins, then freezes, attempting to click on any OBS buttons menus etc after causes OBS to lock up*

**Expected Behavior**
*OBS doesnt lock up i guess?*

**Reproduction Steps**
*Added a usb capture device as a source, applied the stabilzing filter, tested for a while , left it running , looked back it was locked up
Have reboot, restarted and reinstalled the plugin, same result*

**Supporting Evidence**
*If the issue is related to filter performance in a specific scene/scenario, you should provide a YouTube or Twitch link to a video which displays the issue, both with test mode on and off if the filter supports it.*

**Appendix**
*Write anything useful which is not directly related to one of the questions above*

**Comment by Crowsinc** [comment] 2023-02-24 13:15
Hi, could you please provide more information about your usb capture device, so that I may attempt to reproduce the issue?

For example, what is the device, what is it doing, are you using Nvidia Broadcast etc.

**Comment by xxameht** [comment] 2023-02-24 23:56
ive used three devices in testing
a remote source, phone using the SRT protocol
and usb capture device with a hdmi camera, hardware ID for the capture
device is USB\VID_534D&PID_2109&REV_2100&MI_00
Also a logitch Brio webcam
No other plugins or overlays were applied to the source

Not using nvidia broadcast, just straight to OBS.

**Comment by xxameht** [comment] 2023-02-26 05:14
dont know if this helps or not, but i tried putting the cam in a scene,
then applying the stabilisation to the scene instead of the source, and it
ran for about 5 hours before locking up OBS

**Comment by Crowsinc** [comment] 2023-02-26 06:14
Do you have the OBS log for that particular instance?

**Comment by Bartek16194** [comment] 2023-05-14 01:38
> Do you have the OBS log for that particular instance?

Same issue here [log](https://cdn.discordapp.com/attachments/987057603005796422/1107029079556898917/2023-05-13_21-15-02.txt)

**Comment by Crowsinc** [comment] 2024-01-21 03:13
Some fixes were introduced in the latest update. I have been unable to verify their effectiveness, however, I'm closing the ticket for now as the code-base has changed almost completely since this issue was raised.

**Closed as completed by Crowsinc** 2024-01-21 03:13 UTC
Labels: Issue
